name: Publish powa-collector-git container images

# Runs on a new commit on the master branch or when receivind a repository
# dispatch event by the name of "powa-collector-git".
on:
  push:
    branches: [master]
  repository_dispatch:
    types: [powa-collector-git]

env:
  ORG: "powateam"
  IMAGE_NAME: "powa-collector-git"
  REGISTRY: "index.docker.io"

jobs:
  build_and_push:
    name: Build powa-collector-git container images and push to Docker hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.ORG }}/${{ env.IMAGE_NAME }}

      - name: Build and push images
        id: push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: ./powa-collector-git
          file: ./powa-collector-git/Containerfile
          push: true
          tags: ${{ env.ORG }}/${{ env.IMAGE_NAME}}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

